// AUTO-GENERATED by scripts/collect-images.mjs — do not edit by hand.
export interface ProductImageSet {
  card: string;
  gallery: string[];
}

export const PRODUCT_IMAGES: Record<string, ProductImageSet> = {
  "australian-sandalwood-oil": {
    "card": "/products/australian-sandalwood-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/australian-sandalwood-oil/hero_45_cinematic.png",
      "/products/australian-sandalwood-oil/with_ingredients.png",
      "/products/australian-sandalwood-oil/marble_light.png",
      "/products/australian-sandalwood-oil/wood_heritage.png",
      "/products/australian-sandalwood-oil/dark_moody.png",
      "/products/australian-sandalwood-oil/macro_detail.png",
      "/products/australian-sandalwood-oil/lifestyle_vanity.png",
      "/products/australian-sandalwood-oil/gift_packaging.png",
      "/products/australian-sandalwood-oil/flat_lay.png"
    ]
  },
  "cardamom-oil": {
    "card": "/products/cardamom-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/cardamom-oil/hero_45_cinematic.png",
      "/products/cardamom-oil/with_ingredients.png",
      "/products/cardamom-oil/marble_light.png",
      "/products/cardamom-oil/wood_heritage.png",
      "/products/cardamom-oil/dark_moody.png",
      "/products/cardamom-oil/macro_detail.png",
      "/products/cardamom-oil/lifestyle_vanity.png",
      "/products/cardamom-oil/gift_packaging.png",
      "/products/cardamom-oil/flat_lay.png"
    ]
  },
  "carrot-seed-oil": {
    "card": "/products/carrot-seed-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/carrot-seed-oil/hero_45_cinematic.png",
      "/products/carrot-seed-oil/with_ingredients.png",
      "/products/carrot-seed-oil/marble_light.png",
      "/products/carrot-seed-oil/wood_heritage.png",
      "/products/carrot-seed-oil/dark_moody.png",
      "/products/carrot-seed-oil/macro_detail.png",
      "/products/carrot-seed-oil/lifestyle_vanity.png",
      "/products/carrot-seed-oil/gift_packaging.png",
      "/products/carrot-seed-oil/flat_lay.png"
    ]
  },
  "chamomile-oil-german-blue": {
    "card": "/products/chamomile-oil-german-blue/hero_45_cinematic.png",
    "gallery": [
      "/products/chamomile-oil-german-blue/hero_45_cinematic.png",
      "/products/chamomile-oil-german-blue/with_ingredients.png",
      "/products/chamomile-oil-german-blue/marble_light.png",
      "/products/chamomile-oil-german-blue/wood_heritage.png",
      "/products/chamomile-oil-german-blue/dark_moody.png",
      "/products/chamomile-oil-german-blue/macro_detail.png",
      "/products/chamomile-oil-german-blue/lifestyle_vanity.png",
      "/products/chamomile-oil-german-blue/gift_packaging.png",
      "/products/chamomile-oil-german-blue/flat_lay.png"
    ]
  },
  "chamomile-oil-german-green": {
    "card": "/products/chamomile-oil-german-green/hero_45_cinematic.png",
    "gallery": [
      "/products/chamomile-oil-german-green/hero_45_cinematic.png",
      "/products/chamomile-oil-german-green/with_ingredients.png",
      "/products/chamomile-oil-german-green/marble_light.png",
      "/products/chamomile-oil-german-green/wood_heritage.png",
      "/products/chamomile-oil-german-green/dark_moody.png",
      "/products/chamomile-oil-german-green/macro_detail.png",
      "/products/chamomile-oil-german-green/lifestyle_vanity.png",
      "/products/chamomile-oil-german-green/gift_packaging.png",
      "/products/chamomile-oil-german-green/flat_lay.png"
    ]
  },
  "cinnamon-oil": {
    "card": "/products/cinnamon-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/cinnamon-oil/hero_45_cinematic.png",
      "/products/cinnamon-oil/with_ingredients.png",
      "/products/cinnamon-oil/marble_light.png",
      "/products/cinnamon-oil/wood_heritage.png",
      "/products/cinnamon-oil/dark_moody.png",
      "/products/cinnamon-oil/macro_detail.png",
      "/products/cinnamon-oil/lifestyle_vanity.png",
      "/products/cinnamon-oil/gift_packaging.png",
      "/products/cinnamon-oil/flat_lay.png"
    ]
  },
  "citronella-oil": {
    "card": "/products/citronella-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/citronella-oil/hero_45_cinematic.png",
      "/products/citronella-oil/with_ingredients.png",
      "/products/citronella-oil/marble_light.png",
      "/products/citronella-oil/wood_heritage.png",
      "/products/citronella-oil/dark_moody.png",
      "/products/citronella-oil/macro_detail.png",
      "/products/citronella-oil/lifestyle_vanity.png",
      "/products/citronella-oil/gift_packaging.png",
      "/products/citronella-oil/flat_lay.png"
    ]
  },
  "clove-bud-oil": {
    "card": "/products/clove-bud-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/clove-bud-oil/hero_45_cinematic.png",
      "/products/clove-bud-oil/with_ingredients.png",
      "/products/clove-bud-oil/marble_light.png",
      "/products/clove-bud-oil/wood_heritage.png",
      "/products/clove-bud-oil/dark_moody.png",
      "/products/clove-bud-oil/macro_detail.png",
      "/products/clove-bud-oil/lifestyle_vanity.png",
      "/products/clove-bud-oil/gift_packaging.png",
      "/products/clove-bud-oil/flat_lay.png"
    ]
  },
  "cypriol-oil": {
    "card": "/products/cypriol-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/cypriol-oil/hero_45_cinematic.png",
      "/products/cypriol-oil/with_ingredients.png",
      "/products/cypriol-oil/marble_light.png",
      "/products/cypriol-oil/wood_heritage.png",
      "/products/cypriol-oil/dark_moody.png",
      "/products/cypriol-oil/macro_detail.png",
      "/products/cypriol-oil/lifestyle_vanity.png",
      "/products/cypriol-oil/gift_packaging.png",
      "/products/cypriol-oil/flat_lay.png"
    ]
  },
  "eucalyptus-oil": {
    "card": "/products/eucalyptus-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/eucalyptus-oil/hero_45_cinematic.png",
      "/products/eucalyptus-oil/with_ingredients.png",
      "/products/eucalyptus-oil/marble_light.png",
      "/products/eucalyptus-oil/wood_heritage.png",
      "/products/eucalyptus-oil/dark_moody.png",
      "/products/eucalyptus-oil/macro_detail.png",
      "/products/eucalyptus-oil/lifestyle_vanity.png",
      "/products/eucalyptus-oil/gift_packaging.png",
      "/products/eucalyptus-oil/flat_lay.png"
    ]
  },
  "frankincense-oil": {
    "card": "/products/frankincense-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/frankincense-oil/hero_45_cinematic.png",
      "/products/frankincense-oil/with_ingredients.png",
      "/products/frankincense-oil/marble_light.png",
      "/products/frankincense-oil/wood_heritage.png",
      "/products/frankincense-oil/dark_moody.png",
      "/products/frankincense-oil/macro_detail.png",
      "/products/frankincense-oil/lifestyle_vanity.png",
      "/products/frankincense-oil/gift_packaging.png",
      "/products/frankincense-oil/flat_lay.png"
    ]
  },
  "indian-sandalwood-oil": {
    "card": "/products/indian-sandalwood-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/indian-sandalwood-oil/hero_45_cinematic.png",
      "/products/indian-sandalwood-oil/with_ingredients.png",
      "/products/indian-sandalwood-oil/marble_light.png",
      "/products/indian-sandalwood-oil/wood_heritage.png",
      "/products/indian-sandalwood-oil/dark_moody.png",
      "/products/indian-sandalwood-oil/macro_detail.png",
      "/products/indian-sandalwood-oil/lifestyle_vanity.png",
      "/products/indian-sandalwood-oil/gift_packaging.png",
      "/products/indian-sandalwood-oil/flat_lay.png"
    ]
  },
  "kapoor-kachri-oil": {
    "card": "/products/kapoor-kachri-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/kapoor-kachri-oil/hero_45_cinematic.png",
      "/products/kapoor-kachri-oil/with_ingredients.png",
      "/products/kapoor-kachri-oil/marble_light.png",
      "/products/kapoor-kachri-oil/wood_heritage.png",
      "/products/kapoor-kachri-oil/dark_moody.png",
      "/products/kapoor-kachri-oil/macro_detail.png",
      "/products/kapoor-kachri-oil/lifestyle_vanity.png",
      "/products/kapoor-kachri-oil/gift_packaging.png",
      "/products/kapoor-kachri-oil/flat_lay.png"
    ]
  },
  "lavender-oil": {
    "card": "/products/lavender-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/lavender-oil/hero_45_cinematic.png",
      "/products/lavender-oil/with_ingredients.png",
      "/products/lavender-oil/marble_light.png",
      "/products/lavender-oil/wood_heritage.png",
      "/products/lavender-oil/dark_moody.png",
      "/products/lavender-oil/macro_detail.png",
      "/products/lavender-oil/lifestyle_vanity.png",
      "/products/lavender-oil/gift_packaging.png",
      "/products/lavender-oil/flat_lay.png"
    ]
  },
  "lemon-oil": {
    "card": "/products/lemon-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/lemon-oil/hero_45_cinematic.png",
      "/products/lemon-oil/with_ingredients.png",
      "/products/lemon-oil/marble_light.png",
      "/products/lemon-oil/wood_heritage.png",
      "/products/lemon-oil/dark_moody.png",
      "/products/lemon-oil/macro_detail.png",
      "/products/lemon-oil/lifestyle_vanity.png",
      "/products/lemon-oil/gift_packaging.png",
      "/products/lemon-oil/flat_lay.png"
    ]
  },
  "lemongrass-oil": {
    "card": "/products/lemongrass-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/lemongrass-oil/hero_45_cinematic.png",
      "/products/lemongrass-oil/with_ingredients.png",
      "/products/lemongrass-oil/marble_light.png",
      "/products/lemongrass-oil/wood_heritage.png",
      "/products/lemongrass-oil/dark_moody.png",
      "/products/lemongrass-oil/macro_detail.png",
      "/products/lemongrass-oil/lifestyle_vanity.png",
      "/products/lemongrass-oil/gift_packaging.png",
      "/products/lemongrass-oil/flat_lay.png"
    ]
  },
  "morpankhi-oil": {
    "card": "/products/morpankhi-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/morpankhi-oil/hero_45_cinematic.png",
      "/products/morpankhi-oil/with_ingredients.png",
      "/products/morpankhi-oil/marble_light.png",
      "/products/morpankhi-oil/wood_heritage.png",
      "/products/morpankhi-oil/dark_moody.png",
      "/products/morpankhi-oil/macro_detail.png",
      "/products/morpankhi-oil/lifestyle_vanity.png",
      "/products/morpankhi-oil/gift_packaging.png",
      "/products/morpankhi-oil/flat_lay.png"
    ]
  },
  "palmarosa-oil": {
    "card": "/products/palmarosa-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/palmarosa-oil/hero_45_cinematic.png",
      "/products/palmarosa-oil/with_ingredients.png",
      "/products/palmarosa-oil/marble_light.png",
      "/products/palmarosa-oil/wood_heritage.png",
      "/products/palmarosa-oil/dark_moody.png",
      "/products/palmarosa-oil/macro_detail.png",
      "/products/palmarosa-oil/lifestyle_vanity.png",
      "/products/palmarosa-oil/gift_packaging.png",
      "/products/palmarosa-oil/flat_lay.png"
    ]
  },
  "patchouli-oil": {
    "card": "/products/patchouli-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/patchouli-oil/hero_45_cinematic.png",
      "/products/patchouli-oil/with_ingredients.png",
      "/products/patchouli-oil/marble_light.png",
      "/products/patchouli-oil/wood_heritage.png",
      "/products/patchouli-oil/dark_moody.png",
      "/products/patchouli-oil/macro_detail.png",
      "/products/patchouli-oil/lifestyle_vanity.png",
      "/products/patchouli-oil/gift_packaging.png",
      "/products/patchouli-oil/flat_lay.png"
    ]
  },
  "peppermint-oil-mentha-arvensis": {
    "card": "/products/peppermint-oil-mentha-arvensis/hero_45_cinematic.png",
    "gallery": [
      "/products/peppermint-oil-mentha-arvensis/hero_45_cinematic.png",
      "/products/peppermint-oil-mentha-arvensis/with_ingredients.png",
      "/products/peppermint-oil-mentha-arvensis/marble_light.png",
      "/products/peppermint-oil-mentha-arvensis/wood_heritage.png",
      "/products/peppermint-oil-mentha-arvensis/dark_moody.png",
      "/products/peppermint-oil-mentha-arvensis/macro_detail.png",
      "/products/peppermint-oil-mentha-arvensis/lifestyle_vanity.png",
      "/products/peppermint-oil-mentha-arvensis/gift_packaging.png",
      "/products/peppermint-oil-mentha-arvensis/flat_lay.png"
    ]
  },
  "rosemary-oil": {
    "card": "/products/rosemary-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/rosemary-oil/hero_45_cinematic.png",
      "/products/rosemary-oil/with_ingredients.png",
      "/products/rosemary-oil/marble_light.png",
      "/products/rosemary-oil/wood_heritage.png",
      "/products/rosemary-oil/dark_moody.png",
      "/products/rosemary-oil/macro_detail.png",
      "/products/rosemary-oil/lifestyle_vanity.png",
      "/products/rosemary-oil/gift_packaging.png",
      "/products/rosemary-oil/flat_lay.png"
    ]
  },
  "spikenard-oil": {
    "card": "/products/spikenard-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/spikenard-oil/hero_45_cinematic.png",
      "/products/spikenard-oil/with_ingredients.png",
      "/products/spikenard-oil/marble_light.png",
      "/products/spikenard-oil/wood_heritage.png",
      "/products/spikenard-oil/dark_moody.png",
      "/products/spikenard-oil/macro_detail.png",
      "/products/spikenard-oil/lifestyle_vanity.png",
      "/products/spikenard-oil/gift_packaging.png",
      "/products/spikenard-oil/flat_lay.png"
    ]
  },
  "sugandh-kokila-oil": {
    "card": "/products/sugandh-kokila-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/sugandh-kokila-oil/hero_45_cinematic.png",
      "/products/sugandh-kokila-oil/with_ingredients.png",
      "/products/sugandh-kokila-oil/marble_light.png",
      "/products/sugandh-kokila-oil/wood_heritage.png",
      "/products/sugandh-kokila-oil/dark_moody.png",
      "/products/sugandh-kokila-oil/macro_detail.png",
      "/products/sugandh-kokila-oil/lifestyle_vanity.png",
      "/products/sugandh-kokila-oil/gift_packaging.png",
      "/products/sugandh-kokila-oil/flat_lay.png"
    ]
  },
  "sugandh-mantri-oil": {
    "card": "/products/sugandh-mantri-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/sugandh-mantri-oil/hero_45_cinematic.png",
      "/products/sugandh-mantri-oil/with_ingredients.png",
      "/products/sugandh-mantri-oil/marble_light.png",
      "/products/sugandh-mantri-oil/wood_heritage.png",
      "/products/sugandh-mantri-oil/dark_moody.png",
      "/products/sugandh-mantri-oil/macro_detail.png",
      "/products/sugandh-mantri-oil/lifestyle_vanity.png",
      "/products/sugandh-mantri-oil/gift_packaging.png",
      "/products/sugandh-mantri-oil/flat_lay.png"
    ]
  },
  "sweet-basil-oil": {
    "card": "/products/sweet-basil-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/sweet-basil-oil/hero_45_cinematic.png",
      "/products/sweet-basil-oil/with_ingredients.png",
      "/products/sweet-basil-oil/marble_light.png",
      "/products/sweet-basil-oil/wood_heritage.png",
      "/products/sweet-basil-oil/dark_moody.png",
      "/products/sweet-basil-oil/macro_detail.png",
      "/products/sweet-basil-oil/lifestyle_vanity.png",
      "/products/sweet-basil-oil/gift_packaging.png",
      "/products/sweet-basil-oil/flat_lay.png"
    ]
  },
  "tagetes-oil": {
    "card": "/products/tagetes-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/tagetes-oil/hero_45_cinematic.png",
      "/products/tagetes-oil/with_ingredients.png",
      "/products/tagetes-oil/marble_light.png",
      "/products/tagetes-oil/wood_heritage.png",
      "/products/tagetes-oil/dark_moody.png",
      "/products/tagetes-oil/macro_detail.png",
      "/products/tagetes-oil/lifestyle_vanity.png",
      "/products/tagetes-oil/gift_packaging.png",
      "/products/tagetes-oil/flat_lay.png"
    ]
  },
  "tea-tree-oil": {
    "card": "/products/tea-tree-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/tea-tree-oil/hero_45_cinematic.png",
      "/products/tea-tree-oil/with_ingredients.png",
      "/products/tea-tree-oil/marble_light.png",
      "/products/tea-tree-oil/wood_heritage.png",
      "/products/tea-tree-oil/dark_moody.png",
      "/products/tea-tree-oil/macro_detail.png",
      "/products/tea-tree-oil/lifestyle_vanity.png",
      "/products/tea-tree-oil/gift_packaging.png",
      "/products/tea-tree-oil/flat_lay.png"
    ]
  },
  "vetiver-oil": {
    "card": "/products/vetiver-oil/hero_45_cinematic.png",
    "gallery": [
      "/products/vetiver-oil/hero_45_cinematic.png",
      "/products/vetiver-oil/with_ingredients.png",
      "/products/vetiver-oil/marble_light.png",
      "/products/vetiver-oil/wood_heritage.png",
      "/products/vetiver-oil/dark_moody.png",
      "/products/vetiver-oil/macro_detail.png",
      "/products/vetiver-oil/lifestyle_vanity.png",
      "/products/vetiver-oil/gift_packaging.png",
      "/products/vetiver-oil/flat_lay.png"
    ]
  },
  "chandan-attar": {
    "card": "/products/chandan-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/chandan-attar/hero_45_cinematic.png",
      "/products/chandan-attar/with_ingredients.png",
      "/products/chandan-attar/marble_light.png",
      "/products/chandan-attar/wood_heritage.png",
      "/products/chandan-attar/dark_moody.png",
      "/products/chandan-attar/macro_detail.png",
      "/products/chandan-attar/lifestyle_vanity.png",
      "/products/chandan-attar/gift_packaging.png",
      "/products/chandan-attar/flat_lay.png"
    ]
  },
  "genda-attar": {
    "card": "/products/genda-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/genda-attar/hero_45_cinematic.png",
      "/products/genda-attar/with_ingredients.png",
      "/products/genda-attar/marble_light.png",
      "/products/genda-attar/wood_heritage.png",
      "/products/genda-attar/dark_moody.png",
      "/products/genda-attar/macro_detail.png",
      "/products/genda-attar/lifestyle_vanity.png",
      "/products/genda-attar/gift_packaging.png",
      "/products/genda-attar/flat_lay.png"
    ]
  },
  "gulab-attar": {
    "card": "/products/gulab-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/gulab-attar/hero_45_cinematic.png",
      "/products/gulab-attar/with_ingredients.png",
      "/products/gulab-attar/marble_light.png",
      "/products/gulab-attar/wood_heritage.png",
      "/products/gulab-attar/dark_moody.png",
      "/products/gulab-attar/macro_detail.png",
      "/products/gulab-attar/lifestyle_vanity.png",
      "/products/gulab-attar/gift_packaging.png",
      "/products/gulab-attar/flat_lay.png"
    ]
  },
  "hina-attar": {
    "card": "/products/hina-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/hina-attar/hero_45_cinematic.png",
      "/products/hina-attar/with_ingredients.png",
      "/products/hina-attar/marble_light.png",
      "/products/hina-attar/wood_heritage.png",
      "/products/hina-attar/dark_moody.png",
      "/products/hina-attar/macro_detail.png",
      "/products/hina-attar/lifestyle_vanity.png",
      "/products/hina-attar/gift_packaging.png",
      "/products/hina-attar/flat_lay.png"
    ]
  },
  "kesar-attar": {
    "card": "/products/kesar-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/kesar-attar/hero_45_cinematic.png",
      "/products/kesar-attar/with_ingredients.png",
      "/products/kesar-attar/marble_light.png",
      "/products/kesar-attar/wood_heritage.png",
      "/products/kesar-attar/dark_moody.png",
      "/products/kesar-attar/macro_detail.png",
      "/products/kesar-attar/lifestyle_vanity.png",
      "/products/kesar-attar/gift_packaging.png",
      "/products/kesar-attar/flat_lay.png"
    ]
  },
  "kewda-attar": {
    "card": "/products/kewda-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/kewda-attar/hero_45_cinematic.png",
      "/products/kewda-attar/with_ingredients.png",
      "/products/kewda-attar/marble_light.png",
      "/products/kewda-attar/wood_heritage.png",
      "/products/kewda-attar/dark_moody.png",
      "/products/kewda-attar/macro_detail.png",
      "/products/kewda-attar/lifestyle_vanity.png",
      "/products/kewda-attar/gift_packaging.png",
      "/products/kewda-attar/flat_lay.png"
    ]
  },
  "khus-attar": {
    "card": "/products/khus-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/khus-attar/hero_45_cinematic.png",
      "/products/khus-attar/with_ingredients.png",
      "/products/khus-attar/marble_light.png",
      "/products/khus-attar/wood_heritage.png",
      "/products/khus-attar/dark_moody.png",
      "/products/khus-attar/macro_detail.png",
      "/products/khus-attar/lifestyle_vanity.png",
      "/products/khus-attar/gift_packaging.png",
      "/products/khus-attar/flat_lay.png"
    ]
  },
  "mehandi-attar": {
    "card": "/products/mehandi-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/mehandi-attar/hero_45_cinematic.png",
      "/products/mehandi-attar/with_ingredients.png",
      "/products/mehandi-attar/marble_light.png",
      "/products/mehandi-attar/wood_heritage.png",
      "/products/mehandi-attar/dark_moody.png",
      "/products/mehandi-attar/macro_detail.png",
      "/products/mehandi-attar/lifestyle_vanity.png",
      "/products/mehandi-attar/gift_packaging.png",
      "/products/mehandi-attar/flat_lay.png"
    ]
  },
  "mitti-attar": {
    "card": "/products/mitti-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/mitti-attar/hero_45_cinematic.png",
      "/products/mitti-attar/with_ingredients.png",
      "/products/mitti-attar/marble_light.png",
      "/products/mitti-attar/wood_heritage.png",
      "/products/mitti-attar/dark_moody.png",
      "/products/mitti-attar/macro_detail.png",
      "/products/mitti-attar/lifestyle_vanity.png",
      "/products/mitti-attar/gift_packaging.png",
      "/products/mitti-attar/flat_lay.png"
    ]
  },
  "mora-attar": {
    "card": "/products/mora-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/mora-attar/hero_45_cinematic.png",
      "/products/mora-attar/with_ingredients.png",
      "/products/mora-attar/marble_light.png",
      "/products/mora-attar/wood_heritage.png",
      "/products/mora-attar/dark_moody.png",
      "/products/mora-attar/macro_detail.png",
      "/products/mora-attar/lifestyle_vanity.png",
      "/products/mora-attar/gift_packaging.png",
      "/products/mora-attar/flat_lay.png"
    ]
  },
  "motia-belated-attar": {
    "card": "/products/motia-belated-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/motia-belated-attar/hero_45_cinematic.png",
      "/products/motia-belated-attar/with_ingredients.png",
      "/products/motia-belated-attar/marble_light.png",
      "/products/motia-belated-attar/wood_heritage.png",
      "/products/motia-belated-attar/dark_moody.png",
      "/products/motia-belated-attar/macro_detail.png",
      "/products/motia-belated-attar/lifestyle_vanity.png",
      "/products/motia-belated-attar/gift_packaging.png",
      "/products/motia-belated-attar/flat_lay.png"
    ]
  },
  "mukhallat-attar": {
    "card": "/products/mukhallat-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/mukhallat-attar/hero_45_cinematic.png",
      "/products/mukhallat-attar/with_ingredients.png",
      "/products/mukhallat-attar/marble_light.png",
      "/products/mukhallat-attar/wood_heritage.png",
      "/products/mukhallat-attar/dark_moody.png",
      "/products/mukhallat-attar/macro_detail.png",
      "/products/mukhallat-attar/lifestyle_vanity.png",
      "/products/mukhallat-attar/gift_packaging.png",
      "/products/mukhallat-attar/flat_lay.png"
    ]
  },
  "oudh-attar": {
    "card": "/products/oudh-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/oudh-attar/hero_45_cinematic.png",
      "/products/oudh-attar/with_ingredients.png",
      "/products/oudh-attar/marble_light.png",
      "/products/oudh-attar/wood_heritage.png",
      "/products/oudh-attar/dark_moody.png",
      "/products/oudh-attar/macro_detail.png",
      "/products/oudh-attar/lifestyle_vanity.png",
      "/products/oudh-attar/gift_packaging.png",
      "/products/oudh-attar/flat_lay.png"
    ]
  },
  "shamama-attar": {
    "card": "/products/shamama-attar/hero_45_cinematic.png",
    "gallery": [
      "/products/shamama-attar/hero_45_cinematic.png",
      "/products/shamama-attar/with_ingredients.png",
      "/products/shamama-attar/marble_light.png",
      "/products/shamama-attar/wood_heritage.png",
      "/products/shamama-attar/dark_moody.png",
      "/products/shamama-attar/macro_detail.png",
      "/products/shamama-attar/lifestyle_vanity.png",
      "/products/shamama-attar/gift_packaging.png",
      "/products/shamama-attar/flat_lay.png"
    ]
  },
  "ruh-genda": {
    "card": "/products/ruh-genda/hero_45_cinematic.png",
    "gallery": [
      "/products/ruh-genda/hero_45_cinematic.png",
      "/products/ruh-genda/with_ingredients.png",
      "/products/ruh-genda/marble_light.png",
      "/products/ruh-genda/wood_heritage.png",
      "/products/ruh-genda/dark_moody.png",
      "/products/ruh-genda/macro_detail.png",
      "/products/ruh-genda/lifestyle_vanity.png",
      "/products/ruh-genda/gift_packaging.png",
      "/products/ruh-genda/flat_lay.png"
    ]
  },
  "ruh-gulab": {
    "card": "/products/ruh-gulab/hero_45_cinematic.png",
    "gallery": [
      "/products/ruh-gulab/hero_45_cinematic.png",
      "/products/ruh-gulab/with_ingredients.png",
      "/products/ruh-gulab/marble_light.png",
      "/products/ruh-gulab/wood_heritage.png",
      "/products/ruh-gulab/dark_moody.png",
      "/products/ruh-gulab/macro_detail.png",
      "/products/ruh-gulab/lifestyle_vanity.png",
      "/products/ruh-gulab/gift_packaging.png",
      "/products/ruh-gulab/flat_lay.png"
    ]
  },
  "ruh-kewda": {
    "card": "/products/ruh-kewda/hero_45_cinematic.png",
    "gallery": [
      "/products/ruh-kewda/hero_45_cinematic.png",
      "/products/ruh-kewda/with_ingredients.png",
      "/products/ruh-kewda/marble_light.png",
      "/products/ruh-kewda/wood_heritage.png",
      "/products/ruh-kewda/dark_moody.png",
      "/products/ruh-kewda/macro_detail.png",
      "/products/ruh-kewda/lifestyle_vanity.png",
      "/products/ruh-kewda/gift_packaging.png",
      "/products/ruh-kewda/flat_lay.png"
    ]
  },
  "ruh-khus": {
    "card": "/products/ruh-khus/hero_45_cinematic.png",
    "gallery": [
      "/products/ruh-khus/hero_45_cinematic.png",
      "/products/ruh-khus/with_ingredients.png",
      "/products/ruh-khus/marble_light.png",
      "/products/ruh-khus/wood_heritage.png",
      "/products/ruh-khus/dark_moody.png",
      "/products/ruh-khus/macro_detail.png",
      "/products/ruh-khus/lifestyle_vanity.png",
      "/products/ruh-khus/gift_packaging.png",
      "/products/ruh-khus/flat_lay.png"
    ]
  },
  "ruh-motia": {
    "card": "/products/ruh-motia/hero_45_cinematic.png",
    "gallery": [
      "/products/ruh-motia/hero_45_cinematic.png",
      "/products/ruh-motia/with_ingredients.png",
      "/products/ruh-motia/marble_light.png",
      "/products/ruh-motia/wood_heritage.png",
      "/products/ruh-motia/dark_moody.png",
      "/products/ruh-motia/macro_detail.png",
      "/products/ruh-motia/lifestyle_vanity.png",
      "/products/ruh-motia/gift_packaging.png",
      "/products/ruh-motia/flat_lay.png"
    ]
  },
  "one-million": {
    "card": "/products/one-million/hero_45_cinematic.png",
    "gallery": [
      "/products/one-million/hero_45_cinematic.png",
      "/products/one-million/with_ingredients.png",
      "/products/one-million/marble_light.png",
      "/products/one-million/wood_heritage.png",
      "/products/one-million/dark_moody.png",
      "/products/one-million/macro_detail.png",
      "/products/one-million/lifestyle_vanity.png",
      "/products/one-million/gift_packaging.png",
      "/products/one-million/flat_lay.png"
    ]
  },
  "emperio-armani": {
    "card": "/products/emperio-armani/hero_45_cinematic.png",
    "gallery": [
      "/products/emperio-armani/hero_45_cinematic.png",
      "/products/emperio-armani/with_ingredients.png",
      "/products/emperio-armani/marble_light.png",
      "/products/emperio-armani/wood_heritage.png",
      "/products/emperio-armani/dark_moody.png",
      "/products/emperio-armani/macro_detail.png",
      "/products/emperio-armani/lifestyle_vanity.png",
      "/products/emperio-armani/gift_packaging.png",
      "/products/emperio-armani/flat_lay.png"
    ]
  },
  "armani-code-men": {
    "card": "/products/armani-code-men/hero_45_cinematic.png",
    "gallery": [
      "/products/armani-code-men/hero_45_cinematic.png",
      "/products/armani-code-men/with_ingredients.png",
      "/products/armani-code-men/marble_light.png",
      "/products/armani-code-men/wood_heritage.png",
      "/products/armani-code-men/dark_moody.png",
      "/products/armani-code-men/macro_detail.png",
      "/products/armani-code-men/lifestyle_vanity.png",
      "/products/armani-code-men/gift_packaging.png",
      "/products/armani-code-men/flat_lay.png"
    ]
  },
  "ombre-leather": {
    "card": "/products/ombre-leather/hero_45_cinematic.png",
    "gallery": [
      "/products/ombre-leather/hero_45_cinematic.png",
      "/products/ombre-leather/with_ingredients.png",
      "/products/ombre-leather/marble_light.png",
      "/products/ombre-leather/wood_heritage.png",
      "/products/ombre-leather/dark_moody.png",
      "/products/ombre-leather/macro_detail.png",
      "/products/ombre-leather/lifestyle_vanity.png",
      "/products/ombre-leather/gift_packaging.png",
      "/products/ombre-leather/flat_lay.png"
    ]
  },
  "most-wanted-by-azaro": {
    "card": "/products/most-wanted-by-azaro/hero_45_cinematic.png",
    "gallery": [
      "/products/most-wanted-by-azaro/hero_45_cinematic.png",
      "/products/most-wanted-by-azaro/with_ingredients.png",
      "/products/most-wanted-by-azaro/marble_light.png",
      "/products/most-wanted-by-azaro/wood_heritage.png",
      "/products/most-wanted-by-azaro/dark_moody.png",
      "/products/most-wanted-by-azaro/macro_detail.png",
      "/products/most-wanted-by-azaro/lifestyle_vanity.png",
      "/products/most-wanted-by-azaro/gift_packaging.png",
      "/products/most-wanted-by-azaro/flat_lay.png"
    ]
  },
  "tamdao-by-dyptique": {
    "card": "/products/tamdao-by-dyptique/hero_45_cinematic.png",
    "gallery": [
      "/products/tamdao-by-dyptique/hero_45_cinematic.png",
      "/products/tamdao-by-dyptique/with_ingredients.png",
      "/products/tamdao-by-dyptique/marble_light.png",
      "/products/tamdao-by-dyptique/wood_heritage.png",
      "/products/tamdao-by-dyptique/dark_moody.png",
      "/products/tamdao-by-dyptique/macro_detail.png",
      "/products/tamdao-by-dyptique/lifestyle_vanity.png",
      "/products/tamdao-by-dyptique/gift_packaging.png",
      "/products/tamdao-by-dyptique/flat_lay.png"
    ]
  },
  "icon-by-dunhill": {
    "card": "/products/icon-by-dunhill/hero_45_cinematic.png",
    "gallery": [
      "/products/icon-by-dunhill/hero_45_cinematic.png",
      "/products/icon-by-dunhill/with_ingredients.png",
      "/products/icon-by-dunhill/marble_light.png",
      "/products/icon-by-dunhill/wood_heritage.png",
      "/products/icon-by-dunhill/dark_moody.png",
      "/products/icon-by-dunhill/macro_detail.png",
      "/products/icon-by-dunhill/lifestyle_vanity.png",
      "/products/icon-by-dunhill/gift_packaging.png",
      "/products/icon-by-dunhill/flat_lay.png"
    ]
  },
  "creed-aventus": {
    "card": "/products/creed-aventus/hero_45_cinematic.png",
    "gallery": [
      "/products/creed-aventus/hero_45_cinematic.png",
      "/products/creed-aventus/with_ingredients.png",
      "/products/creed-aventus/marble_light.png",
      "/products/creed-aventus/wood_heritage.png",
      "/products/creed-aventus/dark_moody.png",
      "/products/creed-aventus/macro_detail.png",
      "/products/creed-aventus/lifestyle_vanity.png",
      "/products/creed-aventus/gift_packaging.png",
      "/products/creed-aventus/flat_lay.png"
    ]
  },
  "burberry-london": {
    "card": "/products/burberry-london/hero_45_cinematic.png",
    "gallery": [
      "/products/burberry-london/hero_45_cinematic.png",
      "/products/burberry-london/with_ingredients.png",
      "/products/burberry-london/marble_light.png",
      "/products/burberry-london/wood_heritage.png",
      "/products/burberry-london/dark_moody.png",
      "/products/burberry-london/macro_detail.png",
      "/products/burberry-london/lifestyle_vanity.png",
      "/products/burberry-london/gift_packaging.png",
      "/products/burberry-london/flat_lay.png"
    ]
  },
  "hugo-boss": {
    "card": "/products/hugo-boss/hero_45_cinematic.png",
    "gallery": [
      "/products/hugo-boss/hero_45_cinematic.png",
      "/products/hugo-boss/with_ingredients.png",
      "/products/hugo-boss/marble_light.png",
      "/products/hugo-boss/wood_heritage.png",
      "/products/hugo-boss/dark_moody.png",
      "/products/hugo-boss/macro_detail.png",
      "/products/hugo-boss/lifestyle_vanity.png",
      "/products/hugo-boss/gift_packaging.png",
      "/products/hugo-boss/flat_lay.png"
    ]
  },
  "good-girl-by-carolina-herrera": {
    "card": "/products/good-girl-by-carolina-herrera/hero_45_cinematic.png",
    "gallery": [
      "/products/good-girl-by-carolina-herrera/hero_45_cinematic.png",
      "/products/good-girl-by-carolina-herrera/with_ingredients.png",
      "/products/good-girl-by-carolina-herrera/marble_light.png",
      "/products/good-girl-by-carolina-herrera/wood_heritage.png",
      "/products/good-girl-by-carolina-herrera/dark_moody.png",
      "/products/good-girl-by-carolina-herrera/macro_detail.png",
      "/products/good-girl-by-carolina-herrera/lifestyle_vanity.png",
      "/products/good-girl-by-carolina-herrera/gift_packaging.png",
      "/products/good-girl-by-carolina-herrera/flat_lay.png"
    ]
  },
  "bombshell-by-victorias-secret": {
    "card": "/products/bombshell-by-victorias-secret/hero_45_cinematic.png",
    "gallery": [
      "/products/bombshell-by-victorias-secret/hero_45_cinematic.png",
      "/products/bombshell-by-victorias-secret/with_ingredients.png",
      "/products/bombshell-by-victorias-secret/marble_light.png",
      "/products/bombshell-by-victorias-secret/wood_heritage.png",
      "/products/bombshell-by-victorias-secret/dark_moody.png",
      "/products/bombshell-by-victorias-secret/macro_detail.png",
      "/products/bombshell-by-victorias-secret/lifestyle_vanity.png",
      "/products/bombshell-by-victorias-secret/gift_packaging.png",
      "/products/bombshell-by-victorias-secret/flat_lay.png"
    ]
  },
  "gucci-flora": {
    "card": "/products/gucci-flora/hero_45_cinematic.png",
    "gallery": [
      "/products/gucci-flora/hero_45_cinematic.png",
      "/products/gucci-flora/with_ingredients.png",
      "/products/gucci-flora/marble_light.png",
      "/products/gucci-flora/wood_heritage.png",
      "/products/gucci-flora/dark_moody.png",
      "/products/gucci-flora/macro_detail.png",
      "/products/gucci-flora/lifestyle_vanity.png",
      "/products/gucci-flora/gift_packaging.png",
      "/products/gucci-flora/flat_lay.png"
    ]
  },
  "gucci-oud": {
    "card": "/products/gucci-oud/hero_45_cinematic.png",
    "gallery": [
      "/products/gucci-oud/hero_45_cinematic.png",
      "/products/gucci-oud/with_ingredients.png",
      "/products/gucci-oud/marble_light.png",
      "/products/gucci-oud/wood_heritage.png",
      "/products/gucci-oud/dark_moody.png",
      "/products/gucci-oud/macro_detail.png",
      "/products/gucci-oud/lifestyle_vanity.png",
      "/products/gucci-oud/gift_packaging.png",
      "/products/gucci-oud/flat_lay.png"
    ]
  },
  "cool-water-men-women": {
    "card": "/products/cool-water-men-women/hero_45_cinematic.png",
    "gallery": [
      "/products/cool-water-men-women/hero_45_cinematic.png",
      "/products/cool-water-men-women/with_ingredients.png",
      "/products/cool-water-men-women/marble_light.png",
      "/products/cool-water-men-women/wood_heritage.png",
      "/products/cool-water-men-women/dark_moody.png",
      "/products/cool-water-men-women/macro_detail.png",
      "/products/cool-water-men-women/lifestyle_vanity.png",
      "/products/cool-water-men-women/gift_packaging.png",
      "/products/cool-water-men-women/flat_lay.png"
    ]
  },
  "cr-7": {
    "card": "/products/cr-7/hero_45_cinematic.png",
    "gallery": [
      "/products/cr-7/hero_45_cinematic.png",
      "/products/cr-7/with_ingredients.png",
      "/products/cr-7/marble_light.png",
      "/products/cr-7/wood_heritage.png",
      "/products/cr-7/dark_moody.png",
      "/products/cr-7/macro_detail.png",
      "/products/cr-7/lifestyle_vanity.png",
      "/products/cr-7/gift_packaging.png",
      "/products/cr-7/flat_lay.png"
    ]
  },
  "chanel-no-5": {
    "card": "/products/chanel-no-5/hero_45_cinematic.png",
    "gallery": [
      "/products/chanel-no-5/hero_45_cinematic.png",
      "/products/chanel-no-5/with_ingredients.png",
      "/products/chanel-no-5/marble_light.png",
      "/products/chanel-no-5/wood_heritage.png",
      "/products/chanel-no-5/dark_moody.png",
      "/products/chanel-no-5/macro_detail.png",
      "/products/chanel-no-5/lifestyle_vanity.png",
      "/products/chanel-no-5/gift_packaging.png",
      "/products/chanel-no-5/flat_lay.png"
    ]
  },
  "gulab-jal": {
    "card": "/products/gulab-jal/hero_45_cinematic.png",
    "gallery": [
      "/products/gulab-jal/hero_45_cinematic.png",
      "/products/gulab-jal/with_ingredients.png",
      "/products/gulab-jal/marble_light.png",
      "/products/gulab-jal/wood_heritage.png",
      "/products/gulab-jal/dark_moody.png",
      "/products/gulab-jal/macro_detail.png",
      "/products/gulab-jal/lifestyle_vanity.png",
      "/products/gulab-jal/gift_packaging.png",
      "/products/gulab-jal/flat_lay.png"
    ]
  },
  "kesar-water": {
    "card": "/products/kesar-water/hero_45_cinematic.png",
    "gallery": [
      "/products/kesar-water/hero_45_cinematic.png",
      "/products/kesar-water/with_ingredients.png",
      "/products/kesar-water/marble_light.png",
      "/products/kesar-water/wood_heritage.png",
      "/products/kesar-water/dark_moody.png",
      "/products/kesar-water/macro_detail.png",
      "/products/kesar-water/lifestyle_vanity.png",
      "/products/kesar-water/gift_packaging.png",
      "/products/kesar-water/flat_lay.png"
    ]
  },
  "kewda-jal": {
    "card": "/products/kewda-jal/hero_45_cinematic.png",
    "gallery": [
      "/products/kewda-jal/hero_45_cinematic.png",
      "/products/kewda-jal/with_ingredients.png",
      "/products/kewda-jal/marble_light.png",
      "/products/kewda-jal/wood_heritage.png",
      "/products/kewda-jal/dark_moody.png",
      "/products/kewda-jal/macro_detail.png",
      "/products/kewda-jal/lifestyle_vanity.png",
      "/products/kewda-jal/gift_packaging.png",
      "/products/kewda-jal/flat_lay.png"
    ]
  },
  "khus-jal": {
    "card": "/products/khus-jal/hero_45_cinematic.png",
    "gallery": [
      "/products/khus-jal/hero_45_cinematic.png",
      "/products/khus-jal/with_ingredients.png",
      "/products/khus-jal/marble_light.png",
      "/products/khus-jal/wood_heritage.png",
      "/products/khus-jal/dark_moody.png",
      "/products/khus-jal/macro_detail.png",
      "/products/khus-jal/lifestyle_vanity.png",
      "/products/khus-jal/gift_packaging.png",
      "/products/khus-jal/flat_lay.png"
    ]
  },
  "panch-pushpa-jal": {
    "card": "/products/panch-pushpa-jal/hero_45_cinematic.png",
    "gallery": [
      "/products/panch-pushpa-jal/hero_45_cinematic.png",
      "/products/panch-pushpa-jal/with_ingredients.png",
      "/products/panch-pushpa-jal/marble_light.png",
      "/products/panch-pushpa-jal/wood_heritage.png",
      "/products/panch-pushpa-jal/dark_moody.png",
      "/products/panch-pushpa-jal/macro_detail.png",
      "/products/panch-pushpa-jal/lifestyle_vanity.png",
      "/products/panch-pushpa-jal/gift_packaging.png",
      "/products/panch-pushpa-jal/flat_lay.png"
    ]
  },
  "premium-rose-mist": {
    "card": "/assets/premiumROSE.jpeg",
    "gallery": [
      "/assets/premiumROSE.jpeg"
    ]
  },
  "rose-chamomile-mist": {
    "card": "/assets/roseCHAMOMILE.jpeg",
    "gallery": [
      "/assets/roseCHAMOMILE.jpeg"
    ]
  }
};
